language: c

sudo: false

matrix:
  include:
    - env: CABALVER=1.18 GHCVER=7.8.4  NETWORK=-fnetwork  HANS=+hans
      addons: {apt: {packages: [cabal-install-1.18,ghc-7.8.4], sources: [hvr-ghc]}}
    - env: CABALVER=1.18 GHCVER=7.8.4  NETWORK=-f-network HANS=+hans
      addons: {apt: {packages: [cabal-install-1.18,ghc-7.8.4], sources: [hvr-ghc]}}
    - env: CABALVER=1.18 GHCVER=7.8.4  NETWORK=-fnetwork  HANS=-hans
      addons: {apt: {packages: [cabal-install-1.18,ghc-7.8.4], sources: [hvr-ghc]}}
    - env: CABALVER=1.18 GHCVER=7.8.4  NETWORK=-f-network HANS=-hans
      addons: {apt: {packages: [cabal-install-1.18,ghc-7.8.4], sources: [hvr-ghc]}}
    - env: CABALVER=1.22 GHCVER=7.10.2 NETWORK=-fnetwork  HANS=+hans
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.3],sources: [hvr-ghc]}}
    - env: CABALVER=1.22 GHCVER=7.10.2 NETWORK=-f-network HANS=+hans
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.3],sources: [hvr-ghc]}}
    - env: CABALVER=1.22 GHCVER=7.10.2 NETWORK=-fnetwork  HANS=-hans
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.3],sources: [hvr-ghc]}}
    - env: CABALVER=1.22 GHCVER=7.10.2 NETWORK=-f-network HANS=-hans
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.3],sources: [hvr-ghc]}}
    - env: CABALVER=1.22 GHCVER=7.10.2 NETWORK=-fnetwork  HANS=+hans
      addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.1],sources: [hvr-ghc]}}
    - env: CABALVER=1.22 GHCVER=7.10.2 NETWORK=-f-network HANS=+hans
      addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.1],sources: [hvr-ghc]}}
    - env: CABALVER=1.22 GHCVER=7.10.2 NETWORK=-fnetwork  HANS=-hans
      addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.1],sources: [hvr-ghc]}}
    - env: CABALVER=1.22 GHCVER=7.10.2 NETWORK=-f-network HANS=-hans
      addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.1],sources: [hvr-ghc]}}
    - env: CABALVER=head GHCVER=head   NETWORK=-fnetwork  HANS=+hans
      addons: {apt: {packages: [cabal-install-head,ghc-head],  sources: [hvr-ghc]}}
    - env: CABALVER=head GHCVER=head   NETWORK=-f-network HANS=+hans
      addons: {apt: {packages: [cabal-install-head,ghc-head],  sources: [hvr-ghc]}}
    - env: CABALVER=head GHCVER=head   NETWORK=-fnetwork  HANS=-hans
      addons: {apt: {packages: [cabal-install-head,ghc-head],  sources: [hvr-ghc]}}
    - env: CABALVER=head GHCVER=head   NETWORK=-f-network HANS=-hans
      addons: {apt: {packages: [cabal-install-head,ghc-head],  sources: [hvr-ghc]}}

  allow_failures:
    - env: CABALVER=head GHCVER=head   NETWORK=-fnetwork  HANS=+hans
    - env: CABALVER=head GHCVER=head   NETWORK=-f-network HANS=+hans
    - env: CABALVER=head GHCVER=head   NETWORK=-fnetwork  HANS=-hans
    - env: CABALVER=head GHCVER=head   NETWORK=-f-network HANS=-hans

before_install:
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
 - cabal sandbox init
 - cabal update
 - cabal install --only-dependencies --enable-tests $NETWORK -f$HANS --constraint="tls $HANS"
 - cabal configure --enable-tests $NETWORK -f$HANS --constraint="tls $HANS"

script:
 - cabal build
 - cabal check
 - cabal test
 - cabal sdist   # tests that a source-distribution can be generated
# Check that the resulting source distribution can be built & installed.
# If there are no other `.tar.gz` files in `dist`, this can be even simpler:
# `cabal install --force-reinstalls dist/*-*.tar.gz`
 - SRC_TGZ=$(cabal info . | awk '{print $2;exit}').tar.gz &&
   (cd dist && cabal install --force-reinstalls $NETWORK -f$HANS --constraint="tls $HANS" "$SRC_TGZ" --enable-tests )


